"""Lineage redirect/410 maps (ADR-0013 Decision 6).

A 301 is an identity claim, so every claim here is proven from the
pinned checkout's own git history — never guessed. Document level: an
old slug redirects only when the rename walk shows continuous identity
to a currently published document. Provision level: an old provision
URL redirects only when its pid survives in the successor at the pinned
snapshot; a pid that does not survive falls to the namespace's 410,
because a permanent redirect would assert an equivalence this layer
cannot prove. Every retired ``(route, slug)`` gets a 410 namespace
entry; a previously published slug with no successor is 410 outright.

The walk reads renames and deletions from one ``git log`` pass over the
pinned commit's first-parent history (the corpus history is linear).
When one path name was retired more than once, the newest retirement
wins: that is the content the URL last served, so it carries the URL's
identity.
"""

import re
import subprocess
from pathlib import Path

from pydantic import BaseModel, ConfigDict

from lovspor.headings import parse_section_heading
from lovspor.publish.companion import companion_json_bytes
from lovspor.publish.inventory import (
    DocumentPlan,
    PublishError,
    PublishInventory,
    Route,
    body_lines,
    normalise_pid,
)
from lovspor.publish.pages import document_url, provision_url
from lovspor.storage.manifest import Manifest

_FOLDER_ROUTES: dict[str, Route] = {"lover": "lov", "forskrifter": "forskrift"}

_DOC_TYPE_ROUTES: dict[str, Route] = {"lov": "lov", "forskrift": "forskrift"}

_UNSAFE_SLUG = re.compile(r'[\s"{}*]')
"""A historical name with whitespace, quotes, braces or a wildcard was
never a servable URL segment and would break the Caddy snippet's
tokenisation — such a path is skipped, not escaped."""


class _Edge(BaseModel):
    """One lineage event, newest-first: a rename (new set) or a delete."""

    model_config = ConfigDict(frozen=True)

    index: int
    sha: str
    old: str
    new: str | None


class RedirectMap(BaseModel):
    """The generated map: proven 301 pairs and 410 namespace prefixes."""

    model_config = ConfigDict(frozen=True)

    redirects: tuple[tuple[str, str], ...]
    gone: tuple[str, ...]


def build_redirect_map(
    corpus: Path,
    sha: str,
    inventory: PublishInventory,
    manifest: Manifest,
) -> RedirectMap:
    """The redirect/410 map for one pinned snapshot, target-validated."""
    edges = _lineage_edges(corpus, sha)
    live = {(plan.route, plan.slug) for plan in inventory.documents}
    retired = _newest_retirement_per_key(edges, live)
    redirects: list[tuple[str, str]] = []
    gone = {f"/{route}/{slug}/" for route, slug in retired}
    by_path = {plan.markdown_path: plan for plan in inventory.documents}
    for key, edge in sorted(retired.items()):
        plan = _terminal_plan(edge, _edges_by_old(edges), by_path)
        if plan is not None:
            redirects.extend(_document_redirects(corpus, edge, plan, f"/{key[0]}/{key[1]}/"))
    gone.update(_removed_record_prefixes(manifest, live))
    redirect_map = RedirectMap(redirects=tuple(sorted(redirects)), gone=tuple(sorted(gone)))
    validate_redirect_targets(redirect_map, inventory)
    return redirect_map


def validate_redirect_targets(
    redirect_map: RedirectMap,
    inventory: PublishInventory,
) -> None:
    """Every emitted 301 must resolve to an emitted canonical page."""
    emitted = _emitted_urls(inventory)
    for source, target in redirect_map.redirects:
        if target not in emitted:
            raise PublishError(
                f"dangling redirect target: {source} -> {target} does not "
                f"resolve to an emitted canonical page (ADR-0013 Decision 6)",
            )


def redirect_map_json(redirect_map: RedirectMap) -> bytes:
    """Deterministic machine-readable artifact; ``gone`` entries are
    namespace prefixes, overridden by any explicit redirect."""
    return companion_json_bytes(
        {
            "schema_version": "1",
            "redirects": [
                {"from": source, "to": target} for source, target in redirect_map.redirects
            ],
            "gone": list(redirect_map.gone),
        },
    )


def caddy_snippet(redirect_map: RedirectMap) -> bytes:
    """The map in the form Caddy serves (ADR-0013 Decisions 6, 8)."""
    lines = [
        "# Generated by lovspor publish-site (ADR-0013 Decision 6). Do not edit.",
        "# Relies on Caddy's default directive order: redir runs before respond,",
        "# so an explicit 301 wins over its namespace's 410 catch-all.",
    ]
    lines.extend(f"redir {source} {target} 301" for source, target in redirect_map.redirects)
    if redirect_map.gone:
        paths = " ".join(f"{prefix} {prefix}*" for prefix in redirect_map.gone)
        lines.append(f"@lovspor_gone path {paths}")
        lines.append("respond @lovspor_gone 410")
    return ("\n".join(lines) + "\n").encode("utf-8")


def _lineage_edges(corpus: Path, sha: str) -> list[_Edge]:
    """Renames and deletions, newest first, from one log pass."""
    result = subprocess.run(  # noqa: S603
        [  # noqa: S607
            "git",
            "-c",
            "core.quotePath=false",
            "log",
            "-M",
            "--diff-filter=RD",
            "--name-status",
            "--format=%x00%H",
            sha,
        ],
        cwd=corpus,
        capture_output=True,
        text=True,
        check=True,
    )
    return _parse_edges(result.stdout)


_RENAME_FIELDS = 3
"""status<TAB>old<TAB>new."""

_DELETE_FIELDS = 2
"""status<TAB>path."""


def _parse_edges(stdout: str) -> list[_Edge]:
    edges: list[_Edge] = []
    sha = ""
    for line in stdout.splitlines():
        if line.startswith("\x00"):
            sha = line[1:]
            continue
        fields = line.split("\t")
        if fields[0].startswith("R") and len(fields) == _RENAME_FIELDS:
            edges.append(_Edge(index=len(edges), sha=sha, old=fields[1], new=fields[2]))
        elif fields[0] == "D" and len(fields) == _DELETE_FIELDS:
            edges.append(_Edge(index=len(edges), sha=sha, old=fields[1], new=None))
    return edges


def _newest_retirement_per_key(
    edges: list[_Edge],
    live: set[tuple[Route, str]],
) -> dict[tuple[Route, str], _Edge]:
    """The newest edge retiring each non-live ``(route, slug)``."""
    retired: dict[tuple[Route, str], _Edge] = {}
    for edge in edges:
        key = _route_slug(edge.old)
        if key is None or key in live:
            continue
        retired.setdefault(key, edge)
    return retired


def _edges_by_old(edges: list[_Edge]) -> dict[str, list[_Edge]]:
    by_old: dict[str, list[_Edge]] = {}
    for edge in edges:
        by_old.setdefault(edge.old, []).append(edge)
    return by_old


def _terminal_plan(
    edge: _Edge,
    by_old: dict[str, list[_Edge]],
    by_path: dict[str, DocumentPlan],
) -> DocumentPlan | None:
    """Follow the file forward in time to a currently published plan.

    From a rename at time t, the file's next event is the *earliest*
    later event naming its new path — the largest index below t in the
    newest-first order. Indices strictly decrease, so the walk always
    terminates. A deletion or an unpublished terminal proves nothing.
    """
    current, index = edge.new, edge.index
    while current is not None:
        later = [e for e in by_old.get(current, []) if e.index < index]
        if not later:
            return by_path.get(current)
        next_edge = max(later, key=lambda e: e.index)
        current, index = next_edge.new, next_edge.index
    return None


def _document_redirects(
    corpus: Path,
    edge: _Edge,
    plan: DocumentPlan,
    prefix: str,
) -> list[tuple[str, str]]:
    """The document 301 plus one 301 per pid surviving in the successor."""
    redirects = [(prefix, document_url(plan))]
    if plan.duplicate_pids:
        return redirects
    emitted_pids = {provision.pid for provision in plan.provisions}
    for pid in sorted(_retired_pids(corpus, edge) & emitted_pids):
        redirects.append((f"{prefix}paragraf/{pid}/", provision_url(plan, pid)))
    return redirects


def _retired_pids(corpus: Path, edge: _Edge) -> set[str]:
    """Pids of the old document as last published: the blob just before
    the retiring commit (first parent; the corpus history is linear).
    An unreadable blob proves nothing, so it yields no 301s."""
    result = subprocess.run(  # noqa: S603
        ["git", "-c", "core.quotePath=false", "show", f"{edge.sha}^:{edge.old}"],  # noqa: S607
        cwd=corpus,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return set()
    return {
        normalise_pid(parsed[0])
        for line in body_lines(result.stdout)
        if (parsed := parse_section_heading(line)) is not None
    }


def _removed_record_prefixes(manifest: Manifest, live: set[tuple[Route, str]]) -> set[str]:
    """Removed manifest records whose file was never deleted or renamed
    still retire their URL; the file's survival leaves no git edge."""
    prefixes: set[str] = set()
    for record in manifest.documents.values():
        if record.status == "current":
            continue
        route = _DOC_TYPE_ROUTES.get(record.doc_type)
        slug = record.slug or _path_stem(record.markdown_path)
        if route is None or slug is None or (route, slug) in live:
            continue
        if not _UNSAFE_SLUG.search(slug):
            prefixes.add(f"/{route}/{slug}/")
    return prefixes


def _route_slug(path: str) -> tuple[Route, str] | None:
    folder, _, name = path.partition("/")
    route = _FOLDER_ROUTES.get(folder)
    if route is None or "/" in name or not name.endswith(".md"):
        return None
    slug = name[: -len(".md")]
    if not slug or _UNSAFE_SLUG.search(slug):
        return None
    return route, slug


def _path_stem(path: str) -> str | None:
    key = _route_slug(path)
    return key[1] if key is not None else None


def _emitted_urls(inventory: PublishInventory) -> set[str]:
    urls = {document_url(plan) for plan in inventory.documents}
    for plan in inventory.documents:
        if plan.duplicate_pids:
            continue
        urls.update(provision_url(plan, provision.pid) for provision in plan.provisions)
    return urls
