"""The staged rehearsal's world: a flat release, a full envelope, both Caddyfiles.

Built once, here, and used twice — by ``scripts/capture_caddy_adapt.py``,
which runs the real ``caddy adapt`` over it and commits the JSON under
``tests/unit/fixtures/caddy_adapt/``, and by
``tests/unit/test_release_staged.py``, which materialises the same tree
under ``tmp_path`` and rewrites the committed JSON's capture prefix onto
it. One builder, so a committed fixture can never describe a tree the
tests do not have.

The previous Caddyfile is ``migrate_fixtures.OLD_CADDYFILE`` — the
repository's at the merge of #268, verbatim — with the ``/var/www``
prefix pointed at the world; the proposed one is
``deploy/digitalocean/Caddyfile``, the file the migration installs, with
only the fragment's default path rewritten. Neither is a sample of a
Caddyfile: both are the ones the box runs.

The corpus tree the old configuration serves through the symlink and the
one inside the envelope hold the *same bytes*, which is the real
situation — one corpus commit, published twice — and the reason the URL
comparison can be about what is served rather than about where from.
"""

import json
from pathlib import Path
from typing import NamedTuple

from lovspor.release.envelope import CORPUS_DIR, FRAGMENT_NAME, SITE_DIR, fragment_text
from tests.unit.migrate_fixtures import OLD_CADDYFILE

CAPTURE_PREFIX = "/var/www"
"""The prefix the committed JSON carries for the served trees, as on the droplet.

Every path under it is rewritten to the world's own root at capture time
and back to the world's own root at load time; nothing under this name is
ever opened.
"""
CAPTURE_ETC = "/etc/caddy"
"""The same, for the world root itself: ``caddy adapt`` puts the Caddyfile's own
absolute path into every ``file_server`` ``hide`` list, and a captured temporary
directory would make the fixture differ on every machine that regenerates it."""
RELEASE_ID = "3d1f7a0c9b2e4856af03c17d5e9b6284fa71c0d38e52194b7c6a0fd8e31b5947"
"""A ``release_content_id``-shaped name: 64 lowercase hex, letters included.

Deliberately not all digits. Caddy's Caddyfile adapter JSON-parses a
``vars`` value, so an all-digit id adapts to a JSON *number* and
``config_pair`` — which takes only a string — would read the
configuration as naming no release at all.
"""
FLAT_RELEASE = "20260901T120000Z-abcdef123456"
"""The pre-envelope release directory name the symlink points at (ADR-0013)."""
CURRENT_SYMLINK = "lovspor-current"
LIVE_SYMLINK = "lovspor-live"
"""A second symlink, pointing at the envelope: only the symlink fixture's roots use it."""

REDIRECT_SOURCE = "/lov/nl-19140101-001-gammel/"
REDIRECT_TARGET = "/lov/nl-19140101-001/"
GONE_PREFIX = "/lov/nl-18990101-009/"
CORPUS_FILES = {
    "robots.txt": "User-agent: *\nAllow: /\n",
    "sitemap.xml": '<?xml version="1.0"?><urlset/>\n',
    "sitemaps/sitemap-lover-1.xml": '<?xml version="1.0"?><urlset/>\n',
    "lov/nl-19140101-001/index.html": "<h1>Kongeriket Noregs grunnlov</h1>\n",
    "forskrift/sf-20200101-002/index.html": "<h1>Forskrift</h1>\n",
    "site-manifest.json": '{"schema_version": "2"}\n',
}
"""What both corpus trees hold; ``site-manifest.json`` is outside the *old* matcher."""
SITE_FILES = {
    "index.html": "<h1>lovspor</h1>\n",
    "observatory/index.html": "<h1>Observatoriet</h1>\n",
    "om/index.html": "<h1>Om lovspor</h1>\n",
    "en/index.html": "<h1>lovspor</h1>\n",
}
LANDING_FILES = {"index.html": "<h1>lovspor</h1>\n", "om/index.html": "<h1>Om</h1>\n"}
"""The hand-written landing pages the old configuration serves everything else from.

``/om/`` is one the ADR does not name: it is in the site class because the
old configuration answers it, not because anything listed it, and the
migrated tree has to answer it too — with text of its own."""
REDIRECT_MAP = (
    "# Generated by lovspor publish-site (ADR-0013 Decision 6). Do not edit.\n"
    "# Relies on Caddy's default directive order: redir runs before respond,\n"
    "# so an explicit 301 wins over its namespace's 410 catch-all.\n"
    f"redir {REDIRECT_SOURCE} {REDIRECT_TARGET} 301\n"
    f"@lovspor_gone path {GONE_PREFIX} {GONE_PREFIX}*\n"
    "respond @lovspor_gone 410\n"
)
"""``redirects.caddy`` in the shape ``publish.redirects.caddy_snippet`` emits."""

PREVIOUS_NAME = "Caddyfile.previous"
PROPOSED_NAME = "Caddyfile.proposed"
DROPS_ROBOTS = "release-drops-robots.caddy"
WRONG_ROOT = "release-wrong-root.caddy"
WRONG_SITE_ROOT = "release-wrong-site-root.caddy"
FOREIGN_MAP = "release-foreign-map.caddy"
SYMLINKED_ROOT = "release-symlinked-root.caddy"


class World(NamedTuple):
    """Where everything the capture and the tests need stands, under one root."""

    root: Path
    previous: Path
    proposed: Path
    release: Path

    @property
    def fragment(self) -> Path:
        return self.release / FRAGMENT_NAME

    def variant(self, name: str) -> Path:
        """A negative fixture's fragment, beside the Caddyfiles rather than in the envelope.

        Where the real one lives on the droplet: the host's Caddyfile
        imports ``/etc/caddy/lovspor-release.caddy``, and ``caddy adapt``
        composes the next release's fragment through the environment
        placeholder. A fragment left inside ``/var/www`` would be caught
        by the corpus step's import assertion before its own property was
        ever reached.
        """
        return self.root / name


def _write(root: Path, files: dict[str, str]) -> None:
    for name, text in files.items():
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def _corpus_tree(root: Path) -> None:
    """One published corpus: the pages, the sitemaps, and the lineage map beside them."""
    _write(root, CORPUS_FILES)
    (root / "redirects.caddy").write_text(REDIRECT_MAP, encoding="utf-8")


def _flat_release(www: Path) -> None:
    """The pre-envelope layout: a dated directory and the symlink Caddy's root names."""
    flat = www / "lovspor-releases-flat" / FLAT_RELEASE
    _corpus_tree(flat)
    (www / CURRENT_SYMLINK).symlink_to(flat)


def _envelope(www: Path) -> Path:
    """A complete envelope: ``corpus/``, ``site/``, the record and the fragment."""
    release = www / "lovspor-releases" / RELEASE_ID
    _corpus_tree(release / CORPUS_DIR)
    _write(release / SITE_DIR, SITE_FILES)
    (release / "release.json").write_text(
        json.dumps({"release_content_id": RELEASE_ID}) + "\n", encoding="utf-8"
    )
    (release / FRAGMENT_NAME).write_text(fragment_text(release, RELEASE_ID), encoding="utf-8")
    (www / LIVE_SYMLINK).symlink_to(release)
    return release


def _variants(root: Path, release: Path) -> None:
    """The three fragments the negative fixtures are adapted from, beside the Caddyfiles.

    Each takes away exactly one of the properties the dry-run asserts and
    leaves the others intact, so a fixture that fails names which assertion
    detected it rather than failing for four reasons at once.
    """
    www = release.parent.parent
    live = www / LIVE_SYMLINK
    flat = (www / "lovspor-releases-flat" / FLAT_RELEASE).as_posix()
    real = fragment_text(release, RELEASE_ID)
    _write(
        root,
        {
            DROPS_ROBOTS: real.replace(" /robots.txt", "", 1),
            WRONG_ROOT: real.replace(f"{release.as_posix()}/{CORPUS_DIR}", flat),
            WRONG_SITE_ROOT: real.replace(
                f"root * {release.as_posix()}/{SITE_DIR}", f"root * {(www / 'lovspor').as_posix()}"
            ),
            FOREIGN_MAP: real.replace(
                f"import {release.as_posix()}/{CORPUS_DIR}/redirects",
                f"import {(www / CURRENT_SYMLINK).as_posix()}/redirects",
            ),
            SYMLINKED_ROOT: real.replace(release.as_posix(), live.as_posix()),
        },
    )


def _caddyfiles(world_root: Path, release: Path, repo: Path) -> tuple[Path, Path]:
    """Both Caddyfiles, pointed at this world and nothing else."""
    previous = world_root / PREVIOUS_NAME
    previous.write_text(
        OLD_CADDYFILE.replace(CAPTURE_PREFIX, (world_root / "www").as_posix()), encoding="utf-8"
    )
    proposed = world_root / PROPOSED_NAME
    source = (repo / "deploy" / "digitalocean" / "Caddyfile").read_text(encoding="utf-8")
    proposed.write_text(
        source.replace("/etc/caddy/lovspor-release.caddy", (release / FRAGMENT_NAME).as_posix()),
        encoding="utf-8",
    )
    return previous, proposed


def build_world(root: Path, repo: Path) -> World:
    """The whole world under ``root``, with both Caddyfiles naming paths inside it."""
    www = root / "www"
    www.mkdir(parents=True, exist_ok=True)
    _write(www / "lovspor", LANDING_FILES)
    _flat_release(www)
    release = _envelope(www)
    _variants(root, release)
    previous, proposed = _caddyfiles(root, release, repo)
    return World(root, previous, proposed, release)


def rehost(text: str, root: Path) -> str:
    """The committed JSON with its capture prefixes pointed at a real ``root``."""
    rehosted = text.replace(CAPTURE_PREFIX, (root / "www").as_posix())
    return rehosted.replace(CAPTURE_ETC, root.as_posix())


def capture_form(text: str, root: Path) -> str:
    """The reverse: a real capture, with the world's own paths put back to the prefixes.

    The served trees first — they live under the world root, so rewriting
    the root first would leave them half-rewritten.
    """
    captured = text.replace((root / "www").as_posix(), CAPTURE_PREFIX)
    return captured.replace(root.as_posix(), CAPTURE_ETC)


def fixture_path(name: str) -> Path:
    return Path(__file__).parent / "fixtures" / "caddy_adapt" / name


def load_adapted(name: str, root: Path) -> object:
    """One committed ``caddy adapt`` fixture, rehosted onto ``root``."""
    return json.loads(rehost(fixture_path(name).read_text(encoding="utf-8"), root))
